version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3002:3002"
    environment:
      - NODE_ENV=development
      - PORT=3002
      - DATABASE_URL=mysql://root:password@db:3306/nodejs_be_plgrnd
      - JWT_SECRET=your_jwt_secret_key
    depends_on:
      - db
    volumes:
      - ./src:/app/src
    restart: unless-stopped

  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_USER=user
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=nodejs_be_plgrnd
    volumes:
      - mysql_data:/var/lib/mysql
      - ./src/database/seeds:/docker-entrypoint-initdb.d
    restart: unless-stopped

  angular_frontend:
    build: ../sports_hub_angular_skeleton
    depends_on:
      - app
    ports:
      - 3000:3000
    restart: always
    environment:
      NG_APP_API_URL: "http://localhost:3002/"

volumes:
  mysql_data: 